Repository qodo-ai/qodo-cover, pull requests merged in 2024-11, with the labels that each got.

#203 dw/debug scan
  cover_agent/main_full_repo.py
Labels: Review effort [1-5]: 2

#202 Auto scan entire repo !
  .github/workflows/ci_pipeline.yml
  Makefile
  README.md
  cover_agent/AICaller.py
  cover_agent/CoverAgent.py
  cover_agent/PromptBuilder.py
  cover_agent/UnitTestGenerator.py
  cover_agent/lsp_logic/logic.py
  cover_agent/lsp_logic/scripts/main.py
  cover_agent/lsp_logic/utils/utils_context.py
  cover_agent/main.py
  cover_agent/main_full_repo.py
  cover_agent/settings/analyze_test_against_context.toml
  cover_agent/settings/config_loader.py
  cover_agent/settings/test_generation_prompt.toml
  cover_agent/utils.py
  cover_agent/version.txt
  poetry.lock
  tests/test_AICaller.py
  tests/test_CoverAgent.py
  tests/test_CoverageProcessor.py
  tests/test_PromptBuilder.py
  tests/test_UnitTestGenerator.py
  tests/test_load_yaml.py
Labels: Review effort [1-5]: 3

#205 Fixed missing TOML.
  Makefile
  cover_agent/version.txt
Labels: Review effort [1-5]: 2

#204 Include files logic improvement
  cover_agent/PromptBuilder.py
  cover_agent/UnitTestGenerator.py
  cover_agent/lsp_logic/utils/utils.py
  cover_agent/lsp_logic/utils/utils_context.py
  cover_agent/settings/config_loader.py
  cover_agent/settings/configuration.toml
  cover_agent/settings/test_generation_prompt.toml
  cover_agent/settings/token_handling.py
  tests/test_UnitTestGenerator.py
Labels: Review effort [1-5]: 4

#207 Adding conf.
  Makefile
  cover_agent/version.txt
Labels: Review effort [1-5]: 1

#206 Split UTGenerator into generator and validator
  cover_agent/CoverAgent.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  tests/test_CoverAgent.py
  tests/test_UnitTestGenerator.py
  tests/test_UnitTestValidator.py
Labels: Review effort [1-5]: 4

#209 Refactor UnitTestValidator to remove duplication of handling report from CoverageProcessing
  cover_agent/UnitTestValidator.py
Labels: Review effort [1-5]: 2

#211 Generate new tests that are focused on the pr changeset
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/main.py
  cover_agent/version.txt
  poetry.lock
  pyproject.toml
  tests/test_CoverAgent.py
  tests/test_UnitTestGenerator.py
  tests/test_UnitTestValidator.py
Labels: Review effort [1-5]: 4

#208 Tr/run a single test
  cover_agent/CoverAgent.py
  cover_agent/Runner.py
  cover_agent/settings/configuration.toml
  cover_agent/utils.py
  tests/test_load_yaml.py
Labels: Review effort [1-5]: 3, Possible security concern

#214 Add 'cover-agent-full-repo' script to pyproject.toml and update READM…
  README.md
  pyproject.toml
Labels: Review effort [1-5]: 1

#215 Tr/poetry fix
  README.md
  cover_agent/AICaller.py
  cover_agent/CoverAgent.py
  cover_agent/Runner.py
  cover_agent/lsp_logic/multilspy/lsp_protocol_handler/lsp_types.py
  cover_agent/lsp_logic/multilspy/multilspy_types.py
  cover_agent/lsp_logic/utils/utils_context.py
  cover_agent/main_full_repo.py
  cover_agent/settings/configuration.toml
  cover_agent/utils.py
  poetry.lock
  pyproject.toml
  tests/test_AICaller.py
Labels: Review effort [1-5]: 1

#219 Adding features doc.
  docs/features.md
Labels: Review effort [1-5]: 1

#217 Update README.md for Azure OpenAI
  README.md
Labels: Review effort [1-5]: 1

#221 [Fix] Added support for parsing reports in Kotlin language.
  cover_agent/CoverageProcessor.py
  tests/test_CoverageProcessor.py
Labels: Review effort [1-5]: 2

#222 Tr/context helper
  cover_agent/lsp_logic/ContextHelper.py
  cover_agent/lsp_logic/logic.py
  cover_agent/lsp_logic/multilspy/language_server.py
  cover_agent/lsp_logic/scripts/main.py
  cover_agent/lsp_logic/utils/utils_context.py
  cover_agent/main_full_repo.py
Labels: Review effort [1-5]: 3

#223 readme cleaning
  README.md
  docs/development.md
  docs/repo_coverage.md
Labels: Review effort [1-5]: 1

#224 CommandLineToRunASingleTest
  cover_agent/CoverAgent.py
  cover_agent/PromptBuilder.py
  cover_agent/main.py
  cover_agent/settings/adapt_test_command_for_a_single_test_via_ai.toml
  cover_agent/settings/config_loader.py
Labels: Review effort [1-5]: 3

#229 Fixed Makefile to always include TOML files.
  Makefile
Labels: Review effort [1-5]: 1

#232 fix: Running get_coverage() and rebuilding prompt.
  cover_agent/CoverAgent.py
  cover_agent/version.txt
Labels: Review effort [1-5]: 2

#233 Dw/split run
  cover_agent/CoverAgent.py
  cover_agent/UnitTestValidator.py
  cover_agent/version.txt
Labels: Review effort [1-5]: 2

#234 Tr/clean and fix refactors
  cover_agent/CoverAgent.py
  cover_agent/PromptBuilder.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/settings/analyze_test_run_failure.toml
  cover_agent/settings/test_generation_prompt.toml
  tests/test_CoverAgent.py
  tests/test_PromptBuilder.py
  tests/test_UnitTestValidator.py
Labels: Review effort [1-5]: 3

#235 add link
  README.md
Labels: Review effort [1-5]: 1
