Repository qodo-ai/qodo-cover, pull requests merged in 2024-08, with the labels that each got.

#148 fixed bug - additional instruction were given twice
  cover_agent/settings/test_generation_prompt.toml
Labels: Review effort [1-5]: 1, Bug fix

#149 fix 'relevant_line_number_to_insert_tests_after' bug
  cover_agent/UnitTestGenerator.py
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#150 Add run of N times for flakiness
  README.md
  cover_agent/CoverAgent.py
  cover_agent/CustomLogger.py
  cover_agent/UnitTestGenerator.py
  cover_agent/main.py
  cover_agent/version.txt
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#143 Provide ability to run test generation without source or test files
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/UnitTestGenerator.py
  cover_agent/main.py
  cover_agent/version.txt
  tests/test_CoverAgent.py
  tests/test_CoverageProcessor.py
  tests/test_version.py
  tests_integration/increase_coverage.py
Labels: enhancement, Review effort [1-5]: 3
