Repository qodo-ai/qodo-cover, pull requests merged in 2024-06, with the labels that each got.

#64 Fix syntax error in test_FilePreprocessor.py to ensure correct pytest execution
  .gitignore
  cover_agent/PromptBuilder.py
  pyproject.toml
  tests/test_AICaller.py
  tests/test_FilePreprocessor.py
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#69 Tr/wandb
  .github/workflows/ci_pipeline.yml
  Makefile
  README.md
  cover_agent/AICaller.py
  cover_agent/CoverAgent.py
  cover_agent/UnitTestGenerator.py
  cover_agent/version.txt
  poetry.lock
  pyproject.toml
  templated_tests/python_fastapi/test_app.py
Labels: documentation, enhancement, dependencies, Review effort [1-5]: 4

#75 Adding more tests + iterative test example.
  tests/test_AICaller.py
  tests/test_PromptBuilder.py
  tests_integration/README.md
  tests_integration/increase_coverage.py
Labels: enhancement, Review effort [1-5]: 2, Tests

#76 Add instructions for how to add new coverage type. Closes #68.
  docs/Add_New_Coverage_Type_Instructions.md
Labels: documentation, Review effort [1-5]: 2

#77 Initial attempt to solve wandb_gql for issues #70.
  .github/workflows/ci_pipeline.yml
  Makefile
  cover_agent/version.txt
Labels: enhancement, configuration changes, Review effort [1-5]: 3

#78 Adding strict-coverage option and removing prompt only.
  cover_agent/CoverAgent.py
  cover_agent/main.py
  cover_agent/version.txt
  tests_integration/test_with_docker.sh
Labels: enhancement, Review effort [1-5]: 3, other

#79 Disabling failing test.
  tests_integration/test_all.sh
Labels: Review effort [1-5]: 2, Tests

#82 Tr/insert line
  Makefile
  cover_agent/UnitTestGenerator.py
  cover_agent/settings/analyze_suite_test_insert_line.toml
  cover_agent/settings/test_generation_prompt.toml
  poetry.lock
  pyproject.toml
  templated_tests/go_webservice/README.md
  tests/test_UnitTestGenerator.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#83 Update README with detailed Python and Java usage instructions
  README.md
  docs/usage_examples.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#86 Added backslash for easier copy and paste. Remove CI job for docs.
  .github/workflows/ci_pipeline.yml
  docs/usage_examples.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#87 Updated Poetry package versions and added more tests.
  poetry.lock
  pyproject.toml
  tests/test_AICaller.py
  tests/test_CoverageProcessor.py
  tests/test_FilePreprocessor.py
  tests_integration/increase_coverage.py
  tests_integration/test_with_docker.sh
Labels: enhancement, Review effort [1-5]: 2, Tests

#91 Adding build support for cross platform.
  Dockerfile
  tests_integration/README.md
  tests_integration/test_all.sh
Labels: documentation, enhancement, Review effort [1-5]: 3

#94 Adding dockerfile and integration test.
  templated_tests/java_gradle/Dockerfile
  tests_integration/test_all.sh
Labels: enhancement, Review effort [1-5]: 3, Tests

#100 Introduce Nightly Regression Pipeline
  .github/workflows/ci_pipeline.yml
  .github/workflows/nightly_regression.yml
  Dockerfile
  cover_agent/version.txt
  templated_tests/java_spring_calculator/Dockerfile
  templated_tests/java_spring_calculator/src/test/java/com/example/calculator/controller/CalculatorControllerTest.java
  templated_tests/js_vanilla/Dockerfile
  tests_integration/README.md
  tests_integration/test_all.sh
Labels: documentation, enhancement, Review effort [1-5]: 3, Tests
