Repository qodo-ai/qodo-cover, pull requests merged in 2024-10, with the labels that each got.

#166 Adding support for `o1-preview`
  cover_agent/AICaller.py
  cover_agent/ReportGenerator.py
  cover_agent/UnitTestGenerator.py
  cover_agent/version.txt
  tests/test_AICaller.py
  tests/test_CoverAgent.py
  tests/test_PromptBuilder.py
  tests/test_ReportGenerator.py
  tests/test_UnitTestDB.py
  tests/test_UnitTestGenerator.py
  tests/test_load_yaml.py
  tests/test_main.py
  tests_integration/increase_coverage.py
Labels: enhancement, Review effort [1-5]: 3, tests

#132 Added support for Jacoco XML parsing
  cover_agent/CoverageProcessor.py
  tests/test_CoverageProcessor.py
Labels: enhancement, Review effort [1-5]: 3, bug fix

#182 Fixed prompt instructions for class delimiter insertions.
  cover_agent/settings/analyze_suite_test_insert_line.toml
  cover_agent/version.txt
Labels: documentation, enhancement, Review effort [1-5]: 2

#193 Nightly Integration Tests: Upgrade Deprecated Action Versions
  .github/workflows/nightly_regression.yml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#194 Add "Repo of the Day" badge to README
  README.md
Labels: Review effort [1-5]: 1

#198 full support of o1 models + Update LLM dependencies in pyproject.toml to latest versions
  cover_agent/AICaller.py
  cover_agent/UnitTestGenerator.py
  poetry.lock
  pyproject.toml
  tests/test_AICaller.py
Labels: Review effort [1-5]: 2

#201 🗒️ Improve README for devs (running the app locally)
  README.md
Labels: Review effort [1-5]: 1

#200 LSP for python
  cover_agent/lsp_logic/file_map/Acknowledgment.md
  cover_agent/lsp_logic/file_map/file_map.py
  cover_agent/lsp_logic/file_map/queries/get_queries.py
  cover_agent/lsp_logic/file_map/queries/tree-sitter-c-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-c_sharp-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-cpp-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-elisp-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-elixir-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-elm-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-go-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-java-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-javascript-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-ocaml-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-php-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-python-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-ql-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-ruby-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-rust-tags.scm
  cover_agent/lsp_logic/file_map/queries/tree-sitter-typescript-tags.scm
  cover_agent/lsp_logic/logic.py
  cover_agent/lsp_logic/multilspy/Acknowledgment.md
  cover_agent/lsp_logic/multilspy/__init__.py
  cover_agent/lsp_logic/multilspy/language_server.py
  cover_agent/lsp_logic/multilspy/language_servers/jedi_language_server/initialize_params.json
  cover_agent/lsp_logic/multilspy/language_servers/jedi_language_server/jedi_server.py
  cover_agent/lsp_logic/multilspy/lsp_protocol_handler/lsp_constants.py
  cover_agent/lsp_logic/multilspy/lsp_protocol_handler/lsp_requests.py
  cover_agent/lsp_logic/multilspy/lsp_protocol_handler/lsp_types.py
  cover_agent/lsp_logic/multilspy/lsp_protocol_handler/server.py
  cover_agent/lsp_logic/multilspy/multilspy_config.py
  cover_agent/lsp_logic/multilspy/multilspy_exceptions.py
  cover_agent/lsp_logic/multilspy/multilspy_logger.py
  cover_agent/lsp_logic/multilspy/multilspy_settings.py
  cover_agent/lsp_logic/multilspy/multilspy_types.py
  cover_agent/lsp_logic/multilspy/multilspy_utils.py
  cover_agent/lsp_logic/multilspy/type_helpers.py
  cover_agent/lsp_logic/scripts/main.py
  cover_agent/lsp_logic/utils/important_files_logic.py
  cover_agent/lsp_logic/utils/io.py
  cover_agent/lsp_logic/utils/utils.py
  poetry.lock
  pyproject.toml
Labels: Review effort [1-5]: 4
