Repository qodo-ai/qodo-cover, pull requests merged in 2024-07, with the labels that each got.

#112 Updated make installer instructions.
  README.md
Labels: documentation, Review effort [1-5]: 1

#111 Add C templated test
  templated_tests/README.md
  templated_tests/c_cli/.gitignore
  templated_tests/c_cli/Dockerfile
  templated_tests/c_cli/README.md
  templated_tests/c_cli/build_and_test_with_coverage.sh
  templated_tests/c_cli/calc.c
  templated_tests/c_cli/calc.h
  templated_tests/c_cli/main.c
  templated_tests/c_cli/test_calc.c
  tests_integration/test_all.sh
  tests_integration/test_with_docker.sh
Labels: enhancement, Tests, Review effort [1-5]: 4

#113 Add C++ templated test
  templated_tests/README.md
  templated_tests/cpp_cli/.gitignore
  templated_tests/cpp_cli/CMakeLists.txt
  templated_tests/cpp_cli/Dockerfile
  templated_tests/cpp_cli/README.md
  templated_tests/cpp_cli/build_and_test_with_coverage.sh
  templated_tests/cpp_cli/calculator.cpp
  templated_tests/cpp_cli/calculator.hpp
  templated_tests/cpp_cli/main.cpp
  templated_tests/cpp_cli/test_calculator.cpp
  tests_integration/test_all.sh
Labels: enhancement, Review effort [1-5]: 3, Tests

#116 Added docstrings and moved to total token count
  cover_agent/AICaller.py
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/UnitTestGenerator.py
  cover_agent/version.txt
  templated_tests/python_fastapi/test_app.py
  tests/test_AICaller.py
  tests/test_CoverageProcessor.py
  tests/test_FilePreprocessor.py
  tests/test_PromptBuilder.py
  tests/test_UnitTestGenerator.py
  tests_integration/increase_coverage.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#118 Fixed usage example shell commands.
  docs/usage_examples.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#121 Add ruby example
  templated_tests/README.md
  templated_tests/ruby_sinatra/Dockerfile
  templated_tests/ruby_sinatra/Gemfile
  templated_tests/ruby_sinatra/README.md
  templated_tests/ruby_sinatra/app.rb
  templated_tests/ruby_sinatra/test_app.rb
  tests_integration/test_all.sh
Labels: enhancement, Review effort [1-5]: 3, Tests

#97 fix get file base name error in when the operating system is Windows #96
  cover_agent/PromptBuilder.py
Labels: Review effort [1-5]: 2, Bug fix

#122 Added C# example project.
  templated_tests/README.md
  templated_tests/csharp_webservice/.gitignore
  templated_tests/csharp_webservice/CalculatorApi.Tests/CalculatorApi.Tests.csproj
  templated_tests/csharp_webservice/CalculatorApi.Tests/CalculatorControllerTests.cs
  templated_tests/csharp_webservice/CalculatorApi/CalculatorApi.csproj
  templated_tests/csharp_webservice/CalculatorApi/CalculatorController.cs
  templated_tests/csharp_webservice/CalculatorApi/Program.cs
  templated_tests/csharp_webservice/CalculatorApi/Properties/launchSettings.json
  templated_tests/csharp_webservice/CalculatorApi/appsettings.Development.json
  templated_tests/csharp_webservice/CalculatorApi/appsettings.json
  templated_tests/csharp_webservice/Dockerfile
  templated_tests/csharp_webservice/README.md
  tests_integration/test_all.sh
Labels: enhancement, Review effort [1-5]: 3, Tests

#123 Adding Typescript example project.
  templated_tests/README.md
  templated_tests/ruby_sinatra/Gemfile
  templated_tests/typescript_calculator/.gitignore
  templated_tests/typescript_calculator/Dockerfile
  templated_tests/typescript_calculator/README.md
  templated_tests/typescript_calculator/package-lock.json
  templated_tests/typescript_calculator/package.json
  templated_tests/typescript_calculator/src/index.html
  templated_tests/typescript_calculator/src/index.ts
  templated_tests/typescript_calculator/src/modules/Calculator.ts
  templated_tests/typescript_calculator/src/styles.scss
  templated_tests/typescript_calculator/tests/Calculator.test.ts
  templated_tests/typescript_calculator/tsconfig.json
  tests_integration/test_all.sh
Labels: documentation, enhancement, Review effort [1-5]: 3, Tests

#125 Add top level sequence diagram
  docs/Top_Level_Sequence_Diagram.md
Labels: documentation, Review effort [1-5]: 1

#130 Refactor top level modules into smaller functions.
  cover_agent/CoverAgent.py
  cover_agent/UnitTestGenerator.py
  cover_agent/version.txt
Labels: enhancement, Review effort [1-5]: 4

#134 Revert "Refactor top level modules into smaller functions."
  cover_agent/CoverAgent.py
  cover_agent/UnitTestGenerator.py
  cover_agent/version.txt
Labels: enhancement, Bug fix

#135 Adding React example.
  templated_tests/react_calculator/.gitignore
  templated_tests/react_calculator/Dockerfile
  templated_tests/react_calculator/README.md
  templated_tests/react_calculator/package.json
  templated_tests/react_calculator/public/index.html
  templated_tests/react_calculator/src/index.js
  templated_tests/react_calculator/src/modules/Calculator.css
  templated_tests/react_calculator/src/modules/Calculator.js
  templated_tests/react_calculator/src/setupTests.js
  templated_tests/react_calculator/src/tests/Calculator.test.js
  tests_integration/test_all.sh
Labels: enhancement, Review effort [1-5]: 3, Tests

#137 Added LCOV support and applying it to templated C test.
  cover_agent/CoverageProcessor.py
  cover_agent/version.txt
  tests/test_CoverageProcessor.py
  tests_integration/test_all.sh
  tests_integration/test_with_docker.sh
Labels: enhancement, Review effort [1-5]: 3, Tests

#138 Adding workflow and touching C template.
  .github/workflows/templated_test_publish_pipeline.yml
  templated_tests/c_cli/README.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#139 Add option for docker image in nightly regression testing
  templated_tests/cpp_cli/README.md
  templated_tests/csharp_webservice/README.md
  templated_tests/go_webservice/README.md
  templated_tests/java_gradle/README.md
  templated_tests/js_vanilla/README.md
  templated_tests/python_fastapi/README.md
  templated_tests/react_calculator/README.md
  templated_tests/ruby_sinatra/README.md
  tests_integration/test_all.sh
  tests_integration/test_with_docker.sh
Labels: documentation, enhancement, Review effort [1-5]: 3

#141 Adding README for java calculator.
  .github/workflows/templated_test_publish_pipeline.yml
  templated_tests/README.md
  templated_tests/java_spring_calculator/README.md
Labels: documentation, Review effort [1-5]: 1

#142 Update Typescript README
  templated_tests/typescript_calculator/README.md
Labels: documentation, Review effort [1-5]: 1

#140 Moving to docker images for regression testing
  tests_integration/test_all.sh
Labels: enhancement, Review effort [1-5]: 2, Tests
