Repository qodo-ai/qodo-cover, pull requests merged in 2025-02, with the labels that each got.

#274 o3-mini support
  cover_agent/AICaller.py
  poetry.lock
  pyproject.toml
Labels: Review effort [1-5]: 1

#275 Update version.txt
  cover_agent/version.txt
Labels: Review effort [1-5]: 1

#276 Fixing version for action.
  .github/workflows/ci_pipeline.yml
  cover_agent/version.txt
Labels: Review effort [1-5]: 1

#279 bump version
  cover_agent/version.txt
  tests_integration/test_all.sh
Labels: Review effort [1-5]: 1

#286 Update README.md
  README.md
Labels: Review effort 1/5

#287 Update README.md
  README.md
Labels: Review effort 1/5

#282 Updating AgentCompletion to require updated parameters from issue.
  cover_agent/AICaller.py
  cover_agent/AgentCompletionABC.py
  cover_agent/CoverAgent.py
  cover_agent/DefaultAgentCompletion.py
  cover_agent/PromptBuilder.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/settings/test_generation_prompt.toml
  cover_agent/utils.py
  cover_agent/version.txt
  tests/test_AICaller.py
  tests/test_PromptBuilder.py
  tests/test_UnitTestGenerator.py
  tests/test_UnitTestValidator.py
  tests_integration/test_all.sh
  tests_integration/test_with_docker.sh
Labels: Review effort 4/5

#291 Calling object after being instantiated.
  cover_agent/CoverAgent.py
  cover_agent/version.txt
Labels: Review effort 2/5

#290 show warning instead of assert
  cover_agent/CoverageProcessor.py
  tests/test_CoverageProcessor.py
Labels: Review effort 2/5

#292 Update version.txt
  cover_agent/version.txt
Labels: Review effort 1/5

#293 fix test command
  cover_agent/CoverAgent.py
  cover_agent/version.txt
Labels: Review effort 2/5

#301 Incrementing to Python 3.13 max version.
  cover_agent/version.txt
  poetry.lock
  pyproject.toml
Labels: Review effort 2/5

#303 Running Black formatter on code.
  cover_agent/AICaller.py
  cover_agent/AgentCompletionABC.py
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/DefaultAgentCompletion.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/lsp_logic/multilspy/language_server.py
  cover_agent/lsp_logic/multilspy/lsp_protocol_handler/server.py
  cover_agent/utils.py
  tests/test_DefaultAgentCompletion.py
  tests/test_UnitTestGenerator.py
  tests/test_UnitTestValidator.py
  tests_integration/increase_coverage.py
Labels: Review effort 2/5

#307 Adding argument.
  cover_agent/UnitTestValidator.py
Labels: Review effort 1/5

#308 Increase test coverage
  cover_agent/UnitTestValidator.py
  cover_agent/version.txt
  tests/test_AICaller.py
  tests/test_AgentCompletionABC.py
  tests/test_CoverAgent.py
  tests/test_CoverageProcessor.py
  tests/test_FilePreprocessor.py
  tests/test_ReportGenerator.py
  tests/test_UnitTestDB.py
  tests/test_UnitTestGenerator.py
  tests/test_UnitTestValidator.py
  tests/test_load_yaml.py
  tests/test_main.py
  tests/test_version.py
  tests_integration/increase_coverage.py
Labels: Review effort 4/5

#309 294 refactor run test gen into three smaller functions
  cover_agent/CoverAgent.py
  cover_agent/version.txt
Labels: Review effort 3/5
