Repository qodo-ai/qodo-cover, pull requests merged in 2025-05, with the labels that each got.

#323 feature/310-2-record-and-replay-feature
  .coveragerc
  .gitignore
  README.md
  cover_agent/AICaller.py
  cover_agent/CoverAgent.py
  cover_agent/ai_caller_replay.py
  cover_agent/constants.py
  cover_agent/main.py
  cover_agent/record_replay_manager.py
  cover_agent/utils.py
  poetry.lock
  pyproject.toml
  pytest.ini
  stored_responses/c_cli_responses_a8d19a85a2bf.yml
  stored_responses/cpp_cli_responses_fa7bddecaf00.yml
  stored_responses/csharp_webservice_responses_e2f8613e13a0.yml
  stored_responses/go_webservice_responses_a304ffed9b66.yml
  stored_responses/java_gradle_responses_3b9f8df90168.yml
  stored_responses/java_spring_calculator_responses_8fa8103663ed.yml
  stored_responses/js_vanilla_responses_22dcab135d5b.yml
  stored_responses/python_fastapi_responses_a9d9de927a82.yml
  stored_responses/react_calculator_responses_55dc635096e8.yml
  stored_responses/ruby_sinatra_responses_45565837e1f3.yml
  stored_responses/typescript_calculator_responses_59a42f4afe25.yml
  tests/test_AICaller.py
  tests/test_CoverAgent.py
  tests/test_CoverageProcessor.py
  tests/test_ai_caller_replay.py
  tests/test_record_replay_manager.py
  tests/test_utils.py
  tests_integration/constants.py
  tests_integration/docker_utils.py
  tests_integration/run_test_all.py
  tests_integration/run_test_with_docker.py
  tests_integration/scenarios.py
  tests_integration/tests/test_docker_utils.py
Labels: Review effort 4/5

#324 feature/298-flag-disable-file-generation
  .coveragerc
  README.md
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/CustomLogger.py
  cover_agent/DefaultAgentCompletion.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/main.py
  cover_agent/utils.py
  cover_agent/version.txt
  docs/database_usage.md
  docs/usage_examples.md
  tests/test_CoverAgent.py
  tests/test_CustomLogger.py
  tests/test_main.py
  tests_integration/README.md
  tests_integration/run_test_all.py
  tests_integration/run_test_with_docker.py
  tests_integration/test_all.sh
  tests_integration/test_with_docker.sh
Labels: Review effort 3/5

#325 feature/299-remove-args-namespace-from-coveragent-constructor
  cover_agent/AICaller.py
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/CustomLogger.py
  cover_agent/Runner.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/__main__.py
  cover_agent/ai_caller_replay.py
  cover_agent/constants.py
  cover_agent/main.py
  cover_agent/record_replay_manager.py
  cover_agent/settings/config_loader.py
  cover_agent/settings/config_schema.py
  cover_agent/settings/configuration.toml
  cover_agent/version.txt
  tests/test_CoverAgent.py
  tests/test_Runner.py
  tests/test_UnitTestValidator.py
  tests/test_config_schema.py
  tests/test_main.py
  tests_integration/docker_utils.py
  tests_integration/increase_coverage.py
  tests_integration/run_test_all.py
  tests_integration/run_test_with_docker.py
  tests_integration/scenarios.py
Labels: Review effort 3/5

#330 Feature-329: Refactor run_tests_all.py to work within pytest framework
  .github/workflows/ci_pipeline.yml
  Makefile
  cover_agent/CoverAgent.py
  cover_agent/UnitTestValidator.py
  cover_agent/__main__.py
  cover_agent/main_full_repo.py
  cover_agent/settings/README.md
  cover_agent/settings/config_schema.py
  cover_agent/settings/configuration.toml
  cover_agent/utils.py
  cover_agent/version.txt
  pytest.ini
  tests/test_CoverAgent.py
  tests/test_config_schema.py
  tests/test_load_yaml.py
  tests_integration/analyze_tests.py
  tests_integration/conftest.py
  tests_integration/docker_utils.py
  tests_integration/run_test_all.py
  tests_integration/run_test_with_docker.py
  tests_integration/test_e2e.py
Labels: Review effort 3/5

#335 Feature-333: Apply isort and black formatting
  cover_agent/agent_completion_abc.py
  cover_agent/ai_caller.py
  cover_agent/ai_caller_replay.py
  cover_agent/cover_agent.py
  cover_agent/coverage_processor.py
  cover_agent/custom_logger.py
  cover_agent/default_agent_completion.py
  cover_agent/file_preprocessor.py
  cover_agent/main.py
  cover_agent/main_full_repo.py
  cover_agent/record_replay_manager.py
  cover_agent/report_generator.py
  cover_agent/runner.py
  cover_agent/settings/config_loader.py
  cover_agent/settings/token_handling.py
  cover_agent/unit_test_db.py
  cover_agent/unit_test_generator.py
  cover_agent/unit_test_validator.py
  cover_agent/utils.py
  docs/usage_examples.md
  tests/test_agent_completion_abc.py
  tests/test_ai_caller.py
  tests/test_config_schema.py
  tests/test_cover_agent.py
  tests/test_coverage_processor.py
  tests/test_custom_logger.py
  tests/test_default_agent_completion.py
  tests/test_file_preprocessor.py
  tests/test_load_yaml.py
  tests/test_main.py
  tests/test_record_replay_manager.py
  tests/test_report_generator.py
  tests/test_runner.py
  tests/test_unit_test_db.py
  tests/test_unit_test_generator.py
  tests/test_unit_test_validator.py
  tests/test_utils.py
  tests/test_version.py
  tests_integration/analyze_tests.py
  tests_integration/docker_utils.py
  tests_integration/increase_coverage.py
  tests_integration/run_test_all.py
  tests_integration/run_test_with_docker.py
  tests_integration/test_e2e.py
  tests_integration/tests/test_docker_utils.py
Labels: Review effort 1/5

#322 Issue 189 Incorrect Java Class Name Identification
  cover_agent/coverage_processor.py
  tests/test_coverage_processor.py
Labels: Review effort 2/5

#332 Feature-331: Add CONTRIBUTING.md file to the project
  CONTRIBUTING.md
  README.md
  docs/development.md
Labels: Review effort 1/5
