Repository qodo-ai/qodo-cover, pull requests merged in 2025-01, with the labels that each got.

#230 Refactored coverage processor in to class hierarchy
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/coverage/processor.py
  cover_agent/version.txt
  tests/coverage/test_processor.py
  tests/test_CoverAgent.py
  tests/test_CoverageProcessor.py
  tests/test_UnitTestGenerator.py
  tests/test_UnitTestValidator.py
Labels: Review effort [1-5]: 4

#255 Empty commit to trigger CI.
  Makefile
  build_helpers/README.md
  build_helpers/anthropic_tokenizer.json
  cover_agent/version.txt
  poetry.lock
  pyproject.toml
Labels: Review effort [1-5]: 1

#256 Setting coverage threshold to 50% for C# tempalted test.
  tests_integration/test_all.sh
Labels: Review effort [1-5]: 1

#258 Updating python call to python3
  Makefile
Labels: Review effort [1-5]: 1

#254 Enhanced coverage processing (#2)
  cover_agent/UnitTestValidator.py
  cover_agent/coverage/processor.py
  cover_agent/version.txt
  tests/coverage/test_processor.py
  tests/test_UnitTestValidator.py
Labels: Review effort [1-5]: 4

#257 Switching from using diff cover executable to diff cover import
  .github/workflows/ci_pipeline.yml
  Makefile
  cover_agent/UnitTestValidator.py
  cover_agent/version.txt
  tests/test_UnitTestValidator.py
Labels: Review effort [1-5]: 2

#260 Add pip install packages for regression test pipeline.
  .github/workflows/nightly_regression.yml
  Makefile
  cover_agent/version.txt
Labels: Review effort [1-5]: 1

#262 Removing bad reference to self.last_coverage_percentages
  cover_agent/UnitTestValidator.py
Labels: Review effort [1-5]: 1

#264 Fix regression on Jacoco coverage & Corbertura
  cover_agent/coverage/processor.py
  cover_agent/version.txt
  tests/coverage/test_processor.py
  tests_integration/test_all.sh
Labels: Review effort [1-5]: 3

#267 Refactor revert
  cover_agent/CoverAgent.py
  cover_agent/CoverageProcessor.py
  cover_agent/UnitTestGenerator.py
  cover_agent/UnitTestValidator.py
  cover_agent/coverage/processor.py
  cover_agent/version.txt
  tests/coverage/test_processor.py
  tests/test_CoverAgent.py
  tests/test_CoverageProcessor.py
  tests/test_UnitTestGenerator.py
  tests/test_UnitTestValidator.py
  tests_integration/test_all.sh
Labels: Review effort [1-5]: 4
